function renderEvolution(){const hofEl=document.getElementById("hof-list");if(hofEl){hofEl.innerHTML=STRAT_LIB.slice(0,5).map((s,i)=>{const rankClass=i===0?"r1":i===1?"r2":i===2?"r3":"r4";return`<div class="hof-item"><span class="hof-rank ${rankClass}">${i+1}</span><div style="flex:1"><div style="font-size:12px;font-weight:700">${s.id} <span class="tag tag-${s.type==='momentum'?'mom':s.type==='drl'?'drl':'ev'}">${s.type}</span></div><div style="font-size:10px;color:var(--text3)">G${s.gen} · 适应度:${s.fit}</div></div></div>`}).join("")}const evoTb=document.getElementById("evo-strat-tbody");if(evoTb){evoTb.innerHTML=STRAT_LIB.slice(0,10).map(s=>`<tr><td class="cyan">${s.id}</td><td><span class="tag tag-${s.type==='momentum'?'mom':s.type==='drl'?'drl':'ev'}">${s.type}</span></td><td>${s.gen}</td><td class="up">${s.fit}</td><td><span class="sdot ${s.status==='active'?'on':s.status==='standby'?'thinking':'off'}"></span>${s.status}</td></tr>`).join("")}}
function renderBrokers(){const el=document.getElementById("broker-cards");if(!el)return;el.innerHTML=S.brokers.map(b=>`<div class="broker-card ${b.id===S.curBroker?'active-broker ':''}${b.st==='off'?'offline':''}"><div style="display:flex;justify-content:space-between;align-items:center"><span style="font-size:14px;font-weight:700;color:${b.id===S.curBroker?'var(--cyan)':'var(--text)'}">${b.id===S.curBroker?'▶ ':''}${b.name}</span><span class="card-badge ${b.st==='on'?'cb-green':'cb-red'}">${b.st==='on'?'● 已连接':'○ 断开'}</span></div><div class="broker-metrics"><div class="bm-item"><div class="bm-v ${b.lat<100?'up':'down'}">${b.lat<9999?b.lat+'ms':'--'}</div><div class="bm-l">延迟</div></div><div class="bm-item"><div class="bm-v">${b.sr||'--'}%</div><div class="bm-l">成功率</div></div><div class="bm-item"><div class="bm-v">${b.sl||'--'}bps</div><div class="bm-l">滑点</div></div><div class="bm-item"><div class="bm-v">${b.sc}</div><div class="bm-l">评分</div></div></div><div style="font-size:11px;color:var(--text3);margin-top:6px">账户:${b.acc} | 佣金:${b.cm.toFixed(3)}%</div></div>`).join("");const histEl=document.getElementById("broker-hist-list");if(histEl)histEl.innerHTML=S.brokerHistory.map(h=>`<div style="padding:6px 0;border-bottom:1px solid var(--border);font-size:11px;display:flex;gap:10px"><span style="color:var(--text3)">${h.t}</span><span class="down">${h.from}</span><i class="fa-solid fa-arrow-right" style="color:var(--text3)"></i><span class="up">${h.to}</span></div>`).join("")}
function renderHistoryTable(data){const tb=document.getElementById("hist-tbody");if(!tb)return;const rows=data||TRADES.slice(0,30);tb.innerHTML=rows.map(t=>`<tr><td>${t.time}</td><td class="cyan">${t.code}</td><td>${t.name}</td><td class="${t.dir==='买入'?'up':'down'}">${t.dir}</td><td>${t.price.toFixed(2)}</td><td>${t.qty}</td><td><span class="tag tag-mom">${t.strategy}</span></td><td>${t.regime}</td><td class="${t.pnl>=0?'up':'down'}">${t.pnl>=0?'+':''}${t.pnl.toFixed(2)}%</td></tr>`).join("")}
function renderExecLog(){const tb=document.getElementById("exec-tbody");if(!tb)return;tb.innerHTML=S.execLog.map(l=>`<tr><td>${l.t}</td><td class="cyan">${l.c}</td><td class="${l.dir.includes('买')?'up':'down'}">${l.dir}</td><td>${l.price.toFixed(2)}</td><td>${l.qty}</td><td>¥${l.amt.toLocaleString()}</td><td class="${l.st==='成交'?'up':'neutral'}">${l.st}</td></tr>`).join("")}
function renderLivePerf(){const el=document.getElementById("live-perf");if(!el)return;el.innerHTML=[{l:'今日收益',v:'+2.34%',cls:'up'},{l:'成交金额',v:'¥151,251',cls:'cyan'},{l:'下单次数',v:'4',cls:''},{l:'成功率',v:'100%',cls:'up'}].map(m=>`<div class="kpi"><div class="kpi-val ${m.cls}">${m.v}</div><div class="kpi-lbl">${m.l}</div></div>`).join("")}
function renderReportList(){const el=document.getElementById("report-list");if(!el)return;const reports=[{type:'morning',label:'晨报',title:'今日晨报 — 震荡市',date:'今天 08:45'},{type:'stock',label:'个股',title:'贵州茅台深度研究',date:'今天 09:28'}];el.innerHTML=reports.map(r=>`<div class="report-card" onclick="genReport('${r.type}')"><span class="rtype-tag rt-${r.type}">${r.label}</span><div style="flex:1"><div style="font-size:13px;color:var(--text)">${r.title}</div><div style="font-size:10px;color:var(--text3);margin-top:2px">${r.date}</div></div></div>`).join("")}
function genReport(type){const titles={morning:'📊 晨报',stock:'📈 个股深度',weekly:'📋 周报',risk:'⚠ 风险预警'};document.getElementById('report-title').textContent=titles[type]||'报告';document.getElementById('report-body').innerHTML=`<div class="m-section"><h4>报告内容</h4><p style="font-size:12px;color:var(--text2)">${type}报告内容...</p></div><div style="display:flex;gap:8px;margin-top:16px"><button class="btn btn-primary btn-sm" onclick="closeModal('modal-report')">关闭</button></div>`;openModal('modal-report')}
function filterStrat(type,el){if(type)STRAT_FILTER=type;if(el){document.querySelectorAll('.filter-chip').forEach(c=>c.classList.remove('active'));el.classList.add('active')}renderStratLib()}
function sortStrategies(){renderStratLib()}
function exportStrategies(){const csv="ID,类型,代际,适应度,收益,夏普,回撤,胜率\n"+STRAT_LIB.map(s=>`${s.id},${s.type},${s.gen},${s.fit},${s.ret}%,${s.sharpe},${s.dd}%,${s.wr}%`).join("\n");const a=document.createElement('a');a.href="data:text/csv;charset=utf-8,"+encodeURIComponent(csv);a.download="strategies.csv";a.click()}
function autoMatchStocks(){STRAT_LIB.forEach(s=>{s.matchedStocks=['600519','000858','300750']});renderStratLib();showNotif("✓ AI智能匹配完成")}
document.addEventListener('DOMContentLoaded',function(){console.log("Alpha V3.0 初始化...");if(document.getElementById('pos-tbody'))renderPositions();if(document.getElementById('sig-tbody'))renderSignals();if(document.getElementById('ag-grid'))renderAgents();if(document.getElementById('heat-grid'))renderHeatGrid();if(document.getElementById('sent-grid'))renderSentiment();if(document.getElementById('sys-snap'))renderSysSnap();if(document.getElementById('sig-ticker'))renderSigTicker();if(document.getElementById('strat-tbody'))renderStratLib();if(document.getElementById('hof-list'))renderEvolution();if(document.getElementById('broker-cards'))renderBrokers();if(document.getElementById('hist-tbody'))renderHistoryTable(TRADES);if(document.getElementById('exec-tbody'))renderExecLog();if(document.getElementById('live-perf'))renderLivePerf();if(document.getElementById('report-list'))renderReportList();if(!S.chartsInit['overview']){S.chartsInit['overview']=true;initPanelCharts('overview')}console.log("Alpha V3.0 初始化完成")});
