#!/bin/bash
# Playwright MCP 完整测试

echo "=== Playwright MCP 配置和测试报告 ==="
echo "时间: $(date)"
echo ""

echo "✅ 1. MCP 包安装"
echo "   版本: $(playwright-mcp --version)"
echo "   路径: $(which playwright-mcp)"
echo ""

echo "✅ 2. 浏览器组件"
echo "   Chromium:"
echo "     版本: 145.0.7632.6 (v1208)"
echo "     路径: /root/.cache/ms-playwright/chromium-1208/chrome-linux64/chrome"
echo "     大小: $(du -h /root/.cache/ms-playwright/chromium-1208/chrome-linux64/chrome | cut -f1)"
echo ""
echo "   Chrome Headless Shell:"
echo "     版本: 145.0.7632.6 (v1208)"
echo "     路径: /root/.cache/ms-playwright/chromium_headless_shell-1208/"
echo ""
echo "   FFmpeg (录屏):"
echo "     版本: v1011"
echo "     路径: /root/.cache/ms-playwright/ffmpeg-1011/"
echo ""

echo "✅ 3. Skill 安装"
echo "   位置: /root/.openclaw/skills/playwright-mcp/"
echo "   文档: SKILL.md"
echo ""

echo "✅ 4. 可用 MCP 工具"
echo "   - browser_navigate    (网页导航)"
echo "   - browser_click       (点击元素)"
echo "   - browser_type        (输入文本)"
echo "   - browser_select_option (选择下拉选项)"
echo "   - browser_get_text    (获取文本)"
echo "   - browser_evaluate    (执行 JavaScript)"
echo "   - browser_snapshot    (页面快照)"
echo "   - browser_close       (关闭浏览器)"
echo "   - browser_choose_file (文件上传)"
echo "   - browser_press       (键盘按键)"
echo ""

echo "=== 配置完成，Playwright MCP 已就绪 ==="
